font:
  normal:
    family: "Hack Nerd Font Mono"
    style: Regular
  size: 13

window:
  # opacity: 0.95
  opacity: 1

cursor:
  style:
    blinking: Always
    blink_interval: 400

schemes:
  solarized: &solarized
    primary:
      background: '0x002b36'
      foreground: '0x839496'

# Normal colors '0x003642'
    normal:
      black:   '0x073642'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0xd33682'
      cyan:    '0x2aa198'
      white:   '0xeee8d5'

# Bright colors
    bright:
      black:   '0x657b83'
      red:     '0xcb4b16'
      green:   '0x586e75'
      yellow:  '0x657b83'
      blue:    '0x839496'
      magenta: '0x6c71c4'
      cyan:    '0x93a1a1'
      white:   '0xfdf6e3'

    gruvbox: &gruvbox
      primary:
        # hard contrast background - '#1d2021'
        background:        &gruvbox_dark_bg '#282828'
        # soft contrast background - '#32302f'
        foreground:        '#fbf1c7'
        bright_foreground: '#f9f5d7'
        dim_foreground:    '#f2e5bc'
      cursor:
        text:   CellBackground
        cursor: CellForeground
      vi_mode_cursor:
        text:   CellBackground
        cursor: CellForeground
      selection:
        text:       CellBackground
        background: CellForeground
      bright:
        black:   '#928374'
        red:     '#fb4934'
        green:   '#b8bb26'
        yellow:  '#fabd2f'
        blue:    '#83a598'
        magenta: '#d3869b'
        cyan:    '#8ec07c'
        white:   '#ebdbb2'
      normal:
        black:   *gruvbox_dark_bg
        red:     '#cc241d'
        green:   '#98971a'
        yellow:  '#d79921'
        blue:    '#458588'
        magenta: '#b16286'
        cyan:    '#689d6a'
        white:   '#a89984'
      dim:
        black:   '#32302f'
        red:     '#9d0006'
        green:   '#79740e'
        yellow:  '#b57614'
        blue:    '#076678'
        magenta: '#8f3f71'
        cyan:    '#427b58'
        white:   '#928374'

  kanagawa: &kanagawa
    primary:
      background: '0x1f1f28'
      foreground: '0xdcd7ba'

    normal:
      black:   '0x090618'
      red:     '0xc34043'
      green:   '0x76946a'
      yellow:  '0xc0a36e'
      blue:    '0x7e9cd8'
      magenta: '0x957fb8'
      cyan:    '0x6a9589'
      white:   '0xc8c093'

    bright:
      black:   '0x727169'
      red:     '0xe82424'
      green:   '0x98bb6c'
      yellow:  '0xe6c384'
      blue:    '0x7fb4ca'
      magenta: '0x938aa9'
      cyan:    '0x7aa89f'
      white:   '0xdcd7ba'

    selection:
      background: '0x2d4f67'
      foreground: '0xc8c093'

    indexed_colors:
      - { index: 16, color: '0xffa066' }
      - { index: 17, color: '0xff5d62' }

# colors: *gruvbox
colors: *kanagawa
